### ISSUE TITLE
Error in some files

### ISSUE THREAD

**Issue by Adafede** [mwang87/LockDown_Challenge_USI#1]
Hi,

Thank you very much for your conversion and making it public.

I think there might be a problem in some files (example [here](https://github.com/mwang87/LockDown_Challenge_USI/blob/77118817706adee9bcb082c4cfef3182b1b52f06/data/mgf/MS/ms_Challenge%201%20MS.mgf#L9)) of some `END IONS` lines not at the right place.

Best :)

**Comment by mwang87** [comment]
good catch. Updated.
